polaris/benchmark/_base.py
- Change the 'all' label for metrics that aggregated across tasks to 'aggregated'. 
- For more context, see https://github.com/polaris-hub/polaris-hub/pull/227
=> Minor: Change 'all' to 'aggregated'

polaris/cli.py, polaris/curation/_data_curator.py, polaris/utils/types.py
- Improve the documentation of the Polaris login CLI to explain the various options. 
---
During user interviews, users were confused by the CLI documentation.
=> Improve the documentation of the Polaris CLI

.github/workflows/code-check.yml, docs/api/hub.polarisfs.md, env.yml, mkdocs.yml, polaris/hub/client.py, polaris/hub/polarisfs.py, polaris/hub/settings.py, polaris/utils/types.py, pyproject.toml
Integrated a read-only version of [Hadrien's POC](https://github.com/polaris-hub/polaris-fs/blob/main/polarisfs/client/fs.py) for the Polaris FSSpec. Some of the major changes include:
- Added a new endpoint in the client to be able to read the zarr file of a dataset.
- Added a new submodule in the hub folder, `polarisfs.py` which contains the FSSpec.
- For read-only implementation, the FSSpec currently supports the `ls` and `cat_file` operations.
- The `ls` function makes a GET request to the Hub's api storage ls endpoint which returns an array of dictionaries, containing the files and directories within a given path in the Cloudflare R2 bucket.
- In the `ls` function, the prefix is required to be removed from each entry as the path provided to the Zarr store contains only the …
=> feature: polaris fsspec basic read only implementation

polaris/hub/client.py, polaris/hub/polarisfs.py, polaris/hub/settings.py, polaris/utils/types.py
Integrated a basic write implementation for Zarr files with the Polaris FSSpec. Some of the major changes include:
- Added a new endpoint in the client to be able to write a zarr file of a Polaris dataset.
- Added two new methods in the FSSpec: `rm` and `pipe_file`
- The `rm` method is currently added as placeholder since it's required for the Zarr writing integration. 
- The `pipe_file` method calls the hub to get a signed URL for a PUT request, then writes the data to the bucket. The S3 bucket uses SHA-256 for data security but it is currently set to None.
---
_Checklist:_
---
=> feature: polaris fsspec write implementation

polaris/hub/settings.py
- Fix a mistake in the defaults of  `PolarisHubSettings`
---
_Checklist:_
---
Seems a temporary change has managed to sneak past our review!
=> Fix default settings for the `PolarisHubSettings`

polaris/hub/client.py, polaris/loader/load.py
- Added the `verify_checksum` parameter to `load_dataset` and `load_benchmark`.
---
_Checklist:_
---
https://github.com/polaris-hub/polaris/pull/77 changed how the checksum is computed, which created errors when loading a dataset or benchmark from the hub. More generally, I think the checksum can be a little brittle so having a way to disable it seems good.
=> Hotfix: Added option to disable the checksum verification

polaris/_artifact.py, polaris/utils/misc.py, tests/conftest.py, tests/test_evaluate.py, tests/test_type_checks.py
- Adds the `version` attribute to the `BaseArtifactModel`. 
---
_Checklist:_
---
If we ever want to change a function that would break backwards compatibility, we now have the opportunity to maintain backwards compatibility by adding conditional logic based on the version. Not saying this should be our preferred approach, but I think it's nevertheless good to have the opportunity.
=> Added the version attribute to the artifact data model

polaris/dataset/_dataset.py, polaris/hub/client.py
- After calling `Dataset.cache()` the `zarr_root` wasn't reset, because of which it was still using the remote archive. 
- The `default_timeout` parameter for the `PolarisHubClient` can be passed to the `httpx.Client` to properly set it as the default
---
_Checklist:_
---
=> Fix a bug in Dataset.cache() and set a default timeout for the PolarisHubClient

polaris/_artifact.py, polaris/dataset/_adapters.py, polaris/dataset/_dataset.py, tests/conftest.py, tests/test_evaluate.py, tests/test_type_checks.py
- Updated the attribute name in the BaseArtifactModel which indicates the current Polaris client version from `version` to `polaris_version`
- Fixed column adapter logic by introducing a conversion map and updating how the conversion is applied on dataset retrieval
---
_Checklist:_
---
=> Updating column adapter logic and usage

polaris/hub/polarisfs.py
Fixed the "connection reset by peer" error that was occurring for uploading zarr archives ~ 100MB. This was done by removing the passing of `content` when requesting a signed URL from the Hub.
---
_Checklist:_
=> Fix "Connection reset by peer" error when uploading large-ish Zarr datasets

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/default-template.md, .github/ISSUE_TEMPLATE/feature-request.md
- Update the issue templates in preparation of a public release.
=> Update issue templates

polaris/dataset/_dataset.py, polaris/hub/client.py, polaris/utils/types.py
Replaced `copy_all` with `copy_store` when copying a Zarr archive to the Hub. The changes should increase efficiency as `copy_store` does not de-compress and re-compress the data during copying ([see documentation here](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.copy_store)).
Below is the impact it had on profiling:
With `copy_all`:
```Profiling Report
====================================================================================================
Date: 2024-04-04
Time: 17:29:52
Size: 953.67 MB
Repeats: 5
Polaris version: 0.0.2.dev191+g82e7db2
Zarr version: 2.17.1
====================================================================================================
Creating the Zarr archive: 0:00:01.344764 ± 0:00:00.151870
Creating dataset from Source …
```
=> feat: Copy a Zarr archive to the Hub using copy_store for increased efficient

docs/api/evaluation.md, polaris/benchmark/_base.py, polaris/evaluate/_metric.py, polaris/utils/types.py, tests/conftest.py, tests/test_evaluate.py, tests/test_integration.py
- Add metric Balanced average precision from sklearn 
- Add metric Absolute Average Fold Error implementation from https://pubs.acs.org/doi/10.1021/acs.chemrestox.3c00305
---
_Checklist:_
---
=> Metrics absolute average fold error

polaris/hub/settings.py
This PR updates the default settings for the client to use the new Clerk production environment.
For local dev, the client now supports using a `.env` file to point to Clerk's development environment. Use these values:
```.env
POLARIS_HUB_URL="http://localhost:3000/"
POLARIS_AUTHORIZE_URL="https://pure-whippet-77.clerk.accounts.dev/oauth/authorize"
POLARIS_TOKEN_FETCH_URL="https://pure-whippet-77.clerk.accounts.dev/oauth/token"
POLARIS_USER_INFO_URL="https://pure-whippet-77.clerk.accounts.dev/oauth/userinfo"
POLARIS_CLIENT_ID="QJg8zadGwjnr6nbN"
```
---
_Checklist:_
---
=> feat: Update settings for production environment

.github/workflows/code-check.yml, polaris/benchmark/_base.py, polaris/cli.py, polaris/evaluate/_results.py, polaris/hub/client.py
This PR removes the optional .env parameter used in certain places, when instantiating a Hub client class. This was overriding the default value set in the `PolarisHubSettings` class. 
---
_Checklist:_
---
=> fix: Client ignoring default .env file

polaris/competition/_competition.py, polaris/evaluate/__init__.py, polaris/hub/client.py, tests/test_competition.py
This PR removes the wrapper around the evaluation logic for use by the hub. Instead we can just call `evaluate_benchmark` directly from there. This requires testing in the context of working competitions, which we will do next. This requires the accompanying PR in the hub, https://github.com/polaris-hub/polaris-hub/pull/338
---
_Checklist:_
---
=> Use evaluation logic directly in hub, no need for wrapper

polaris/competition/_competition.py, polaris/utils/errors.py, tests/test_competition.py
- adds some validation on competition creation to check that all test rows will have at least one value in a target column
---
_Checklist:_
- [-] _Update the API documentation if a new function is added, or an existing one is deleted._
---
This is a small improvement discussed with Andrew before his vacation. We want to make sure that you can't create a competition where there is missing test data.
=> Test that all rows of a competition test set will have at least a value

polaris/hub/client.py
- Fix a bug in the login flow where `self.token` was expected to be an `OAuth2Token` instance, but was `None`
---
_Checklist:_
---
For future reference, this would lead to the following stack-trace: 
```
(polaris) ➜  polaris git:(feat/zarr-checksum) _TYPER_STANDARD_TRACEBACK=1 polaris login --overwrite
Traceback (most recent call last):
File "/Users/cas.wognum/micromamba/envs/polaris/bin/polaris", line 8, in <module>
sys.exit(app())
^^^^^
File "/Users/cas.wognum/micromamba/envs/polaris/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
raise e
File "/Users/cas.wognum/micromamba/envs/polaris/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
return get_command(self)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix auth token being `None` during login

polaris/hub/external_auth_client.py
This PR adds a check, in the external auth token, for the existence of the token before checking its validity. This will prevent an error that breaks the login flow for users who have no cached external auth 
token.
---
_Checklist:_
-
=> fix: Issue where a None token breaks the login flow

polaris/hub/client.py
Updating the `client.upload_dataset` method to only add the `zarrRootPath` field to datasets which make use of Zarr. Otherwise, datasets which do not use make use of Zarr will fail a validation check and cannot be uploaded. 
---
_Checklist:_
~- [ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._~
~- [ ] _Add tests to cover the fixed bug(s) or the newly introduced feature(s) (if appropriate)._~
---
=> Only adding zarrRootPath field to datasets that use Zarr

polaris/benchmark/_base.py
When computing the hash for a benchmark, the benchmark split is included in the hash calculation. The current calculation logic works fine when there is a single test set, but errors when multiple are specified. 
This is because a `split` variable is defined and used during the calculation, but it is only defined when a single test set is specified. This PR ensures the `split` variable is defined in the case of multiple test sets.
---
_Checklist:_
~- [ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._~
~- [ ] _Add tests to cover the fixed bug(s) or the newly introduced feature(s) (if appropriate)._~
~- [ ] _Update the API documentation if a new function is added, or an existing one is deleted._~
---
=> Fix undefined split during checksum calc with multiple test sets

polaris/benchmark/_base.py, tests/test_benchmark.py
This PR enables the definition of zero-shot benchmarks by allowing the train partition of `BenchmarkSpecification` to be an empty list. See #131 
- No more `InvalidBenchmarkError` is raised when `v[0]` is empty in `_validate_split`
- Error message and docstring was adjusted accordingly
---
_Checklist:_
---
=> Allow an empty train partition to support test-set only (e.g. zero-shot) benchmarks

polaris/hub/client.py
- Wrapped the JSON parsing of an HTTP response's body in a `try...except` block. This prevents a `JSONDecodeError` in the event the response does not include JSON. This allows the error to still be handled in a meaningful manner. Errors returned from the Hub should be unaffected and output in the same fashion. 
---
_Checklist:_
---
=> Updating `base_request_to_hub` method to allow handling of responses without json

polaris/benchmark/_base.py, tests/test_evaluate.py
- Added example in `benchmark.evaluation` docstrings to clarify the evaluation inputs.
=> Add examples in evaluation docstring

polaris/hub/client.py
- ~Updated `client.upload_benchmark` method to use the correct, sluggified `owner/name` combination during benchmark upload.~
- Currently, dataset uploads are completed such that the `name` of the dataset is really the `slug`. These two differ in that `slugs` convert underscores to hyphens whereas `names` do not. Because the `name` and `slug` are separate things, and the name of the dataset should be the name (not the slug), this change ensures that user naming is respected on dataset upload.
---
_Checklist:_
---
=> Updating dataset upload to respect `Dataset` name

polaris/benchmark/_base.py, tests/test_benchmark.py
- Updating the `split` field validator in the `BenchmarkSpecification` model to check for duplicates _within_ individual test sets rather than _across_ all test sets
- Added test to ensure duplicates in a nested test set are caught
- Added test to ensure that duplicate indices are allowed across indices
---
_Checklist:_
---
=> Updating split validator to allow duplicates across test sets

docs/quickstart.md, polaris/hub/client.py
- Updated the quickstart guide to include a section about logging in prior to interacting with artifacts on Polaris
- Updated the handling of `client.request` errors such that client-side token errors produce a more useful error message to the user
- Updated the `client.base_request_to_hub` method to provide a more meaningful error message to users when their token expires
---
_Checklist:_
---
=> Improving token errors and quickstart guide 

polaris/_version.py
- Updating the name of the package for which we fetch the client version from. It is currently trying to look for `polaris` when it should be looking for `polaris-lib`. This is needed because all incoming bug reports have the version `dev` instead of the actual release version.
---
_Checklist:_
---
=> Adding correct name of package during version fetch

env.yml, pyproject.toml
This PR pins the Numpy version to 1.x.y, to match the requirement from Biotite, itself required by FastPDB. On a clean virtual env install, the Numpy 2+ raises an error when importing Polaris.
=> fix: Issue with Numpy version requirement from fastpdb/biotite

polaris/dataset/_column.py
A quick PR to remove the Literal wrappers in KnownContentType definition because it was causing display issues in the data viz table
---
_Checklist:_
---
=> Remove literal wrappers in KnownContentType definition 

polaris/dataset/_dataset.py
- Add argument `timeout` to `Dataset.upload_to_hub` function, to keep the consistency to [client function](https://github.com/polaris-hub/polaris/blob/c910f2876ddfae71cf17430035d4bf7a257251eb/polaris/hub/client.py#L537). 
---
_Checklist:_
---
The `timeout` argument is crucial for the success of large dataset uploading.
=> add timeout argument

.github/changelog_config.json
- Added a `other` category to the changelogs that will include any unlabeled PRs.
---
_Checklist:_
---
Sometimes we forget to label a PR. This change to the CICD ensures that those PRs still show up in the changelogs.
=> Chore: Add catch-all 'other' category to the generated changelog

docs/api/dataset.md, docs/quickstart.md, polaris/benchmark/_base.py, polaris/dataset/__init__.py, polaris/dataset/_base.py, polaris/dataset/_column.py, polaris/dataset/_competition_dataset.py, polaris/dataset/_dataset.py, polaris/dataset/_factory.py, polaris/dataset/_subset.py, polaris/dataset/converters/_pdb.py, polaris/dataset/converters/_sdf.py, polaris/dataset/zarr/__init__.py, polaris/dataset/zarr/_checksum.py, polaris/dataset/zarr/_manifest.py, polaris/experimental/_dataset_v2.py, polaris/hub/client.py, polaris/loader/load.py, polaris/mixins/_checksum.py, polaris/utils/errors.py, polaris/utils/misc.py, polaris/utils/types.py, polaris/utils/v2_manifest.py, tests/conftest.py, tests/test_dataset.py, tests/test_dataset_v2.py, tests/test_evaluate.py
- Introduce a new `DatasetV2` class in a new `polaris.experimental` module.
- Explicitly rename the old dataset to `DatasetV1`, but create the `Dataset` alias for it.
- Extract a `BaseDataset` class that encompasses all functionality that is shared between V1 and V2.
- Restricted use of `__getitem__` to only allow indexing a specific value or a row. 
- Add a new Zarr manifest for upload integrity. 
- See #185
---
_Checklist:_
---
Closes https://github.com/polaris-hub/polaris/issues/132
The implementation has been relatively straight-forward given the [PoC](https://github.com/polaris-hub/polaris-private/blob/experiment/belka-dataset/scripts/cas/belka/nb/03.%20Subset%20API.ipynb). There are two points that required some further thinking.
1. **Naming and code organization**: I wasn't sure …
=> XL Datasets: Minimal Zarr-only dataset implementation

polaris/benchmark/_base.py, polaris/dataset/_base.py, polaris/dataset/_competition_dataset.py, polaris/dataset/_dataset.py, polaris/experimental/_dataset_v2.py
- Type the return type of `@model_validator(mode="after")` with `Self`
---
_Checklist:_
---
This came up in #186 , but I only saw it after merging. See https://github.com/polaris-hub/polaris/pull/186#discussion_r1755296478 .
=> Type the return type of `@model_validator(mode="after")` with `Self`

docs/api/evaluation.md, polaris/evaluate/_metric.py, polaris/evaluate/metrics/__init__.py, polaris/evaluate/metrics/docking_metrics.py, polaris/evaluate/metrics/generic_metrics.py, polaris/evaluate/utils.py, polaris/utils/types.py, tests/conftest.py, tests/test_evaluate.py
- Added metric `rmsd_coverage` for docking related benchmarks
- Added unit tests
- Added new target type "docking"
---
_Checklist:_
---
The rmsd metrics are implemented based on the [Posebuster codebase](https://github.com/maabuu/posebusters/blob/main/posebusters/modules/rmsd.py). A few modifications were made, replacing RDKit callables with equivalent Datamol functions. The RMSD calculation was also simplified to evaluate only the first conformer of the predicted molecule and to consider only heavy atoms.
Note: Posebusters provides a series of checkers, known as '[Posebuster Checkers](https://github.com/maabuu/posebusters/tree/main),' to further filter out unwanted docked ligand conformers. To avoid over-complicating Polaris metrics module with case-specific metrics, users should apply …
=> Add ligand RMSD metrics 

polaris/dataset/zarr/_manifest.py
- Update the way we build the Zarr archive manifest to use a single PyArrow table. This yields a reduction of ~90% in size of the resulting manifest, probably due to better compression. (A manifest of 3708 files went from 2.7MB to 119KB.)
---
_Checklist:_
- ~[ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._~
- ~[ ] _Add tests to cover the fixed bug(s) or the newly introduced feature(s) (if appropriate)._~
- ~[ ] _Update the API documentation if a new function is added, or an existing one is deleted._~
---
=> chore: Update dataset manifest build

polaris/dataset/_base.py, polaris/dataset/_dataset.py, polaris/experimental/_dataset_v2.py, polaris/hub/client.py, polaris/hub/external_client.py, polaris/hub/storage.py
- Added support for downloading V2 Datasets from the Hub.
- Given that `authlib >1.3.0` is [not yet available for Conda](https://github.com/conda-forge/authlib-feedstock), we can't assume a [recently merged QoL improvement](https://github.com/lepture/authlib/commit/16fa567110b4bb4094f3ab3a452bafb9945847fb) is available and needed some code to handle the case that `token` is None in `ensure_active_token()`.
- Excluded some fields from the `repr_dict` to prevent excessive compute when visualizing the dataset.
---
_Checklist:_
---
The `client.get_dataset()` tries loading a V1 dataset first, and then the V2 if a 404 is raised. This adds some overhead, but given the deadline I would like us to optimize this later. 
We don't have a great way setup yet to test these changes, so I manually …
=> Feature: Download for V2 datasets

polaris/experimental/_dataset_v2.py
- Computing the zarr checksum manifest properties during caching would fail. We thus exclude these properties from the `model_dump()`
=> Fix: Exclude some computed properties during caching

polaris/__init__.py, polaris/dataset/_base.py, polaris/dataset/zarr/_utils.py, polaris/utils/errors.py, pyproject.toml, tests/conftest.py, tests/test_benchmark.py, tests/test_competition.py, tests/test_dataset.py, tests/test_dataset_v2.py, tests/test_evaluate.py, tests/test_factory.py, tests/test_zarr_checksum.py
- Adds `imagecodecs` as an optional dependency.
- Throw an error with an actionable message when a codec is missing.
- Update test cases to use `tmp_path` rather than `tmpdir` ([ref](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures)).
---
_Checklist:_
---
Out of curiosity: Are there any design patterns to handle optional dependencies in Python systematically? I did a quick Google search, but couldn't find much. Maybe @jstlaurent knows?
=> Chore: Add `imagecodecs` as an optional dependency

polaris/hub/client.py, polaris/hub/settings.py, polaris/hub/storage.py
- Add optional settings for username and password
- Update token fetching from the Hub to use username/password when present
---
_Checklist:_
---
When present, the Polaris Hub client will use the configured `POLARIS_USERNAME` and `POLARIS_PASSWORD` environment variables for authentication to the Hub, rather than an interactive login flow involving a browser session. This will only work for Polaris Hub users that have set a password on their account. The username is one of the email addresses associated with the Polaris Hub account.
This PR depends on a [PR on the Polaris Hub](https://github.com/polaris-hub/polaris-hub/pull/542), to enable the OAuth Resource Owner Password Credentials Grant.
=> feat: Add an optional username/password login mode

polaris/dataset/converters/_pdb.py, polaris/dataset/converters/_sdf.py, polaris/dataset/converters/_zarr.py, polaris/dataset/zarr/_utils.py, polaris/experimental/_dataset_v2.py
- Load Zarr array to memory before converting from Zarr Group to AtomArray for PDB files. 
- Indices into a Zarr Group should always be strings.
---
_Checklist:_
=> Fix: Optimize PDB adapter

.github/workflows/code-check.yml, .github/workflows/doc.yml, .github/workflows/release.yml, .github/workflows/test.yml, polaris/__init__.py, polaris/dataset/zarr/_memmap.py, polaris/hub/client.py, polaris/hub/storage.py, polaris/loader/__init__.py, polaris/loader/load.py, tests/test_hub_integration.py, tests/test_zarr_checksum.py
- Added Windows to the CICD testing matrix.
- Using #221, add integration test with the Hub.
- Switched to `uv` instead of `mamba` for the CICD
- Fix #226 
---
_Checklist:_
---
I created a dedicated test user in Clerk for this. It's credentials have been added to the secrets of this Github repository.
=> Testing: Added Windows to CICD testing matrix, add hub integration test and fix errors

polaris/benchmark/_base.py, polaris/dataset/_base.py, polaris/evaluate/__init__.py, polaris/evaluate/_results.py, polaris/evaluate/utils.py, polaris/hub/client.py
- Update the `upload_results` client method to us the new V2 API endpoint in the Hub
- Tighten types in Pydantic models to reflect the data structure once parsing is complete
- Update client base request method to return the httpx response, in order to make headers accessible.
- Closes [PRO-175]
---
_Checklist:_
---
This PR updates the client to use the new V2 API endpoint for results. This will enable uploading supports for the upcoming V2 Benchmarks. Due to the nature of the result model in the client, which holds 
their related benchmark identitifer but not an object reference, the same endpoint must accomodate both V1 and V2 benchmarks.
I also took the opportunity to tighten the typing in some Pydantic models. We had initially typed our models liberally, to show what could be accepted …
=> feat: Support result upload for XL benchmarks

polaris/dataset/_base.py, polaris/dataset/_dataset.py, polaris/experimental/_dataset_v2.py, polaris/hub/client.py, polaris/hub/storage.py, tests/test_dataset.py
- Implement a custom Zarr store copy operation in the `S3Store`
---
_Checklist:_
---
A recent dataset added to the Hub sported a Zarr archive of modest size, but with a large number of files (194.056 MiB, 5067 files). The large number of files and the overhead of copying them to the Hub storage resulted in a transfer time of over 30 minutes. For comparison, using [Rclone](https://rclone.org/) to transfer the same Zarr archive to the same storage backend required 7 minutes.
The root cause of the client's slow upload lies in the implementation of the [`zarr.copy_store`](https://zarr.readthedocs.io/en/stable/api/convenience.html#zarr.convenience.copy_store) we use in our `StorageSession` class. This implementation makes no assumption about the nature of the source or destination stores, so …
=> chore: Optimize Zarr store copy operation to Hub storage

polaris/benchmark/_base.py, polaris/evaluate/_metric.py, tests/test_benchmark.py
- Add an alias to the `custom_name` to match behavior on Hub. 
- Clarify error message
---
_Checklist:_
---
I'll merge this without review given the urgency.
=> Fix: Add alias for `custom_name` in `Metric`

polaris/__init__.py, polaris/dataset/__init__.py, polaris/dataset/zarr/_codecs.py, polaris/dataset/zarr/codecs.py, tests/test_codecs.py
- Add a custom object codec for RDKit Molecules and Biotite AtomArrays
---
_Checklist:_
---
This PR builds on the discussion in #241. 
The use of custom `numcodecs`-compatible object codecs for use in Zarr seems like a natural interface point to document and implement conversion from and to drug discovery specific format. 
You would simply use this like: 
```py
import zarr
import datamol as dm
from polaris.dataset.zarr._codecs import RDKitMolCodec
root = zarr.open("test.zarr", mode="w")
root.empty("molecules", shape=100, dtype=object, object_codec=RDKitMolCodec(), chunks=(5,))
root["molecules"][0] = dm.to_mol("C1=CC=CC=C1")
```
=> Add custom codecs for RDKit Molecules and Biotite AtomArrays

polaris/dataset/_base.py, polaris/dataset/_dataset_v2.py, polaris/hub/storage.py
- Add a LRU cache to the `S3Store` class, to cache fetched objects
- Add chunk-based iterators, to improve performance when traversing dataset columns
---
_Checklist:_
---
This builds on the work Cas did in `feat/optimize-dataloader`. I increased the number of cached objects in the S3 store, since most of them are small anyway. I also added a Generator-based chunking iterator, that I think is simpler than the class-based approach. It should reduce the amount of decompression that takes place when iterating through a dataset row-by-row.
=> chore: Improve data loading performance in S3 store

.github/workflows/code-check.yml, .github/workflows/doc.yml, .github/workflows/release.yml, .github/workflows/test.yml, .gitignore, env.yml, pyproject.toml, uv.lock
- Add a GitHub Actions job to run the test suite under a Conda environment
- Update the dependency list by removing unused ones
---
_Checklist:_
---
Since we've been tripped by some dependendencies that don't have all platforms supported in Conda, adding a CI flow that will run the tests from a clean Conda environment should raise these issues earlier.
=> chore: Add a CI job to run tests in Conda, to detect dependency failure earlier

env.yml, pyproject.toml, uv.lock
- Pin Boto3 to < 1.36.0, to avoid a breaking change in the checksum request headers
---
_Checklist:_
---
Fixes #246.
Boto3 has changed its [default behavior in 1.36.0](https://github.com/boto/boto3/issues/4392). The header that is now added automatically is not supported by all S3-compatible services, such as Cloudflare R2, which is the backing store for the Polaris Hub storage. The suggested configuration to disable the new behavior does not appear to fix this issue in our case. I've elected to pin the Boto3 version for now.
=> fix: Pin Boto3 version to avoid breaking change

polaris/hub/storage.py, uv.lock
- Explicitly set the region when instantiating a boto3 client, to prevent it from picking one up from some external AWS config
---
_Checklist:_
---
Boto3 can automatically pick up external configuration for AWS, from various places in the environment: env variables, config files in user directory, etc. This recently caused a problem where it picked up a 
region from a user that was not compatible with the Cloudflare R2 bucket we use. Explicitly setting the region when the client is created will avoid this issue in the future.
=> fix: Prevent external AWS configuration from breaking our boto3 config

env.yml, polaris/utils/context.py, pyproject.toml, uv.lock
- Switched from `yaspin` to `Halo` for terminal spinners to fix issues with small terminal widths and improve overall reliability. [Halo](https://github.com/manrajgrover/halo) handles text better and avoids truncation errors.
---
_Checklist:_
---
=> fix: Replace yaspin with halo for spinners

polaris/cli.py, polaris/hub/client.py, polaris/hub/external_client.py, polaris/loader/load.py, polaris/utils/context.py, pyproject.toml, uv.lock
- Make sure the `ensure_active_token` methods will identify that there is no token
- Surface a better error message when it happens, so users can take action to remediate
---
_Checklist:_
---
Adresses #251
This bug fix will better handle cases where the OAuth token is `None`. This might result from a new user that has not logged in, tokens that were not cached, or cached credentials that have 
expired. When the client is used in the loader functions, and one such situation occurs, ane exception will be raised that includes a better, actionable error message for the user.
=> fix: Better handling when no cached token exists, with more decriptive error

polaris/evaluate/_results.py
- Removed the duplicate `CompetitionPredictions` class
---
_Checklist:_
---
We use [`polaris.evaluate._predictions.CompetitionPredictions`](https://github.com/polaris-hub/polaris/blob/main/polaris/evaluate/_predictions.py#L252), we also had [`polaris.evaluate._results.CompetitionPredictions`](https://github.com/polaris-hub/polaris/blob/main/polaris/evaluate/_results.py#L202). Since the latter wasn't used, I deleted it.
=> Chore: Remove duplicate and unused CompetitionPredictions class

polaris/hub/settings.py, tests/test_hub_integration.py
- Update the skip check to skip if either required settings are missing
---
_Checklist:_
---
The previous check would pass if at least one of username or password was set, and the test would fail.
=> chore: Update skip condition for integration tests

polaris/dataset/_subset.py, tests/test_subset.py
- `Subset.as_dataframe()` would raise an error when called on a test set (which hides its targets), this PR allows method to work, just doesn't return targest
---
_Checklist:_
---
Resolves https://github.com/polaris-hub/polaris/issues/257
=> `Subset.as_dataframe()` hides targets instead of raising an error

polaris/dataset/zarr/codecs.py, tests/test_codecs.py
- Always pass bytes to the `VLenBytes` codec, parent class of the `RDKitMolCodec`.
---
_Checklist:_
---
I was running into a Cython issue with a chunk size > 1 because we were passing None rather than bytes.
=> Fix: Always pass bytes in the RDKitMolCodec

env.yml, pyproject.toml, uv.lock
- Update Numpy ceiling to version 2
---
_Checklist:_
---
This PR allows Numpy 2+ as a dependency. The downstream issue with fastpdb seems to have been resolved.
=> chore: Update numpy version restriction

docs/tutorials/create_a_benchmark.ipynb, docs/tutorials/create_a_dataset.ipynb, polaris/_artifact.py, polaris/benchmark/_base.py, polaris/dataset/_base.py, polaris/dataset/_dataset.py, polaris/dataset/_dataset_v2.py, polaris/hub/client.py
- Added version fields `artifact_version` and `artifact_changelog` to benchmarks
- `upload_benchmark` accepts an optional parameter `parent_artifact_id` (owner/slug), which defaults to None
- The benchmark will be uploaded as a subsequent version of the provided parent
- This functionality is different from the previous `upload_as_new_version` param implemented in `feat/artifact-versioning`, and `upload_datasets` has been updated accordingly
- Modified dataset and benchmark `upload_to_hub` functions to also accept `parent_artifact_id`
- Added info about `parent_artifact_id` and uploading new versions of datasets and benchmarks to the documentation
---
_Checklist:_
---
=> feat: Artifact Versioning - upload benchmark

pyproject.toml
- Add a `project.optional-dependencies` to the `pyproject.toml` file
---
_Checklist:_
---
Adresses #274
Using the [PEP 735](https://peps.python.org/pep-0735/) to define dependency groups means they are not recognized as extras when Polaris is specified as a dependency. So doing `pip install 
polaris-lib[codecs]` will not also install `imagecodecs` as a dependency.
We probably have not noticied this behavior when developping the library locally because `uv sync` recognizes the dependency groups.
=> fix: Extras are not recognized and installed

polaris/model/__init__.py
- Added `contributors` field to `Model` class, so users can specify a list of contributors on model upload
---
_Checklist:_
---
=> feat: Model Competitions - Model Contributors

env.yml, pyproject.toml, uv.lock
- Moved FastPDB from a pip dependency to a conda-forge dependency
---
_Checklist:_
---
Adresses issue #276.
By moving the FastPDB dependency to the conda-forge list, we'll prevent users with certain environment configuration from installing an incomplete Polaris.
=> fix: Prevent missing FastPDB on Conda install

docs/tutorials/create_a_dataset.ipynb, docs/tutorials/create_a_model.ipynb, polaris/dataset/_subset.py, polaris/evaluate/_metadata.py, polaris/hub/client.py
- **New Features:**
- Added `list_models` utility function.
- Introduced a **"Create a Model"** tutorial.
- Added `model_artifact_id` as a computed property in `ResultsMetadataV2`.
- **Improvements:**
- Added `code_url` as an alias for `github_url` in `ResultsMetadataV1`.
- Added `report_url` as an alias for `paper_url` in `ResultsMetadataV1`.
- **Bug Fixes:**
- Fixed a bug in result evaluation by using a shallow copy of subsets instead of a deep copy.
- Fixed a bug in the `get_model` method (wrong endpoint URL).
- Fixed a bug in the `_get_v2_benchmark` method (`TypeError: got multiple values for keyword argument 'split'`)
- Fixed typings in the `upload_results` method for `results` param.
- Corrected small typos in docstrings.
---
_Checklist:_
---
<details>
<summary><b>Model Landing and …
=> Client: Model artifact remaining changes

docs/tutorials/create_a_model.ipynb, polaris/benchmark/_base.py, polaris/dataset/_base.py, polaris/hub/client.py, polaris/model/__init__.py
🗝️ [Hub changes here!](https://github.com/polaris-hub/polaris-hub/pull/630)
- Added `artifact_version` and `artifact_version` fields to model artifact
- Modified `upload_to_hub` and `upload_model` functions to accept `parent_artifact_id`, in order to upload a new version of a model
- Updated tutorial to explain how to upload a new version of a model
---
_Checklist:_
=> feat: Model Versioning

polaris/evaluate/_metadata.py
Since we're making [models optional when uploading a v2 result](https://github.com/polaris-hub/polaris-hub/pull/634), this change needs to be made. Otherwise, an error gets thrown when no model is included 😊
---
_Checklist:_
---
=> fix: Allow models to be optional on results v2

polaris/benchmark/_base.py, polaris/dataset/_base.py, polaris/dataset/_dataset.py, polaris/dataset/_dataset_v2.py, polaris/evaluate/_results.py, polaris/hub/client.py, polaris/model/__init__.py, polaris/utils/types.py
This PR removes the `AccessType` type, simplifying the API by eliminating the `access` parameter, which was previously used to specify public or private access when uploading artifacts to the Polaris Hub.
* **Type and Imports Cleanup**:
- Removed `AccessType` from imports in multiple files, including `polaris/benchmark/_base.py`, `polaris/dataset/_base.py`, `polaris/dataset/_dataset.py`, `polaris/dataset/_dataset_v2.py`, `polaris/evaluate/_results.py`, `polaris/hub/client.py`, and `polaris/model/__init__.py`.
* **Parameter Removal in Method Definitions**:
- Removed the `access` parameter from method signatures such as `upload_to_hub` in various modules (`polaris/benchmark/_base.py`, `polaris/dataset/_base.py`, `polaris/dataset/_dataset.py`, `polaris/dataset/_dataset_v2.py`, …
=> Refactor/Chore: Remove access parameters in client
